// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LogLik_cpp
List LogLik_cpp(NumericVector omega, NumericMatrix pi_mat, NumericMatrix R, NumericVector m, NumericMatrix xi_mat, NumericMatrix uniform_j);
RcppExport SEXP _CUBClustR_LogLik_cpp(SEXP omegaSEXP, SEXP pi_matSEXP, SEXP RSEXP, SEXP mSEXP, SEXP xi_matSEXP, SEXP uniform_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi_mat(pi_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi_mat(xi_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type uniform_j(uniform_jSEXP);
    rcpp_result_gen = Rcpp::wrap(LogLik_cpp(omega, pi_mat, R, m, xi_mat, uniform_j));
    return rcpp_result_gen;
END_RCPP
}
// eta_ijk_cpp
NumericVector eta_ijk_cpp(NumericMatrix pi_mat, NumericMatrix R, NumericVector m, NumericMatrix xi_mat, NumericMatrix uniform_j, int K, int J, int n);
RcppExport SEXP _CUBClustR_eta_ijk_cpp(SEXP pi_matSEXP, SEXP RSEXP, SEXP mSEXP, SEXP xi_matSEXP, SEXP uniform_jSEXP, SEXP KSEXP, SEXP JSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pi_mat(pi_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi_mat(xi_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type uniform_j(uniform_jSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_ijk_cpp(pi_mat, R, m, xi_mat, uniform_j, K, J, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CUBClustR_LogLik_cpp", (DL_FUNC) &_CUBClustR_LogLik_cpp, 6},
    {"_CUBClustR_eta_ijk_cpp", (DL_FUNC) &_CUBClustR_eta_ijk_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_CUBClustR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
