# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LogLik_cpp <- function(omega, pi_mat, R, m, xi_mat, uniform_j) {
    .Call(`_CUBClustR_LogLik_cpp`, omega, pi_mat, R, m, xi_mat, uniform_j)
}

.eta_ijk_cpp <- function(pi_mat, R, m, xi_mat, uniform_j, K, J, n) {
    .Call(`_CUBClustR_eta_ijk_cpp`, pi_mat, R, m, xi_mat, uniform_j, K, J, n)
}

